@startuml

skinparam packageStyle rectangle

skinparam monochrome true

top to bottom direction

package "Module Layer" {
  class CredentialModule
}

package "Service Layer" {
  class CredentialService
  class ConnectionService
  class LedgerService
  class IndyHolderService
  class IndyIssuerService
}

package "Repository Layer" {
  class CredentialRepository
}

'Module relations
CredentialModule --> CredentialService
CredentialModule --> ConnectionService

'Service relations
CredentialService -left-> ConnectionService
CredentialService -right-> LedgerService
CredentialService -down-> IndyHolderService
CredentialService -down-> IndyIssuerService

CredentialService -u-> CredentialRepository


@enduml
