@startuml

skinparam packageStyle rectangle
skinparam monochrome true

top to bottom direction

package "Module Layer" {
  class CredentialModule
}

package "Service Layer" {
  abstract CredentialService
  class ConnectionService
  class LedgerService

  ' class IndyVDR
  class CredX
  class IndySDK
  ' class AriesAskar

  ' interface IndyHolderService
  ' class IndySDKHolderService
  ' class SharedLibrariesHolderService


  ' interface IndyIssuerService
  ' class IndySDKIssuerService
  ' class SharedLibrariesIssuerService

  class CredentialServiceV1
  class CredentialServiceV2

  interface CredentialFormat
  class IndyFormat
  class LinkedDataFormat

  interface IndyHolder
  interface IndyIssuer

  class W3CService

}

package "Repository Layer" {
  class CredentialRepository
}

'Module relations
CredentialModule --> CredentialService
CredentialModule --> ConnectionService

'Service relations
CredentialService -left-> ConnectionService
CredentialService -right-> LedgerService
' CredentialService -down-> IndyHolderService
' CredentialService -down-> IndyIssuerService


CredentialServiceV1 -up-|> CredentialService
CredentialServiceV2 -up-|> CredentialService

CredentialService -u-> CredentialRepository

IndyFormat -right-|> CredentialFormat
LinkedDataFormat -left-|> CredentialFormat

CredentialServiceV1 -down-> IndyFormat
CredentialServiceV2 -down-> IndyFormat
CredentialServiceV2 -down-> LinkedDataFormat

IndyFormat -down-> IndyHolder
IndyFormat -down-> IndyIssuer

IndyIssuer -down-> CredX
IndyIssuer -down-> IndySDK

LinkedDataFormat -down-> W3CService

' IndyHolderService -d-> SharedLibrariesHolderService
' IndyHolderService -d-> IndySDKHolderService
' SharedLibrariesHolderService -d-> IndyVDR
' SharedLibrariesHolderService -d-> IndyCredX
' SharedLibrariesHolderService -d-> AriesAskar


' IndyIssuerService -d-> IndySDKIssuerService
' IndyIssuerService -d-> SharedLibrariesIssuerService
' SharedLibrariesIssuerService -d-> IndyVDR
' SharedLibrariesIssuerService -d-> IndyCredX
' SharedLibrariesIssuerService -d-> AriesAskar




@enduml